version: "3.5"
services:
  pfadmin:
    image: jrlehtinen/pfadmin:adaptive
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      #resources:
        #limits:
          #cpus: "0.85"
          #memory: 3200M
    ports:
      - "9999:9999"
    networks:
      - pfnet
  pfengine:
    image: jrlehtinen/pfengine:adaptive
    deploy:
      #placement:
        #constraints: [node.role == worker]
      replicas: 6
      restart_policy:
        condition: on-failure
      #resources:
        #limits:
          #cpus: "0.85"
          #memory: 3200M
    ports:
      - "9031:9031"
    networks:
      - pfnet
networks:
  pfnet:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16